### ISSUE TITLE
Replace `residua-mutf8` with `simd_cesu8`

### ISSUE THREAD

**Issue by seancroach** [azalea-rs/simdnbt#10]
Hello! I'm the author of [`residua-mutf8`](https://github.com/residua/mutf8), the library you currently use to decode and encode UTF-8 to MUTF-8.

It's thanks to `simdnbt` that I entered the rabbit hole of SIMD, and after some tinkering, I made a new crate: [`simd_cesu8`](https://github.com/seancroach/simd_cesu8). Extremely simply, I took inspiration from your ASCII test, inverted it when possible to be a UTF-8 4-byte character (and null for MUTF-8) test, and found a significant performance increase!

I also now have built-in operations for lossy MUTF-8 (and CESU-8) decoding, which might improve the current "interpret MUTF-8 as lossy UTF-8" approach it seems `Mutf8Str::to_string_lossy` takes. 

Review it and see if it's worth adopting; I'd appreciate it a lot.

**Comment by mat-1** [comment]
Oh wow, this is really cool. Thank you for making your MUTF-8 implementation and for telling me about your updated version, it's awesome that my crate inspired you :). I implemented the update to use your new version [here](https://github.com/azalea-rs/simdnbt/commit/7a7e0e2a10de9ed8753090df212f752e887094c4) (I also refactored a little bit and slightly improved my docs which included replacing "M-UTF8" with "MUTF-8", heh).

Something interesting that I noticed is that your check where you call `simdutf8::basic::from_utf8` is slower for plain ASCII than my `is_plain_ascii` check by a significant amount (~220% slower on [one of my benchmarks](https://github.com/azalea-rs/simdnbt/blob/master/simdnbt/benches/mutf8.rs#L9), with `-C target-cpu=native`), so it might be worth PRing them for a faster plain ASCII check.

**Comment by seancroach** [comment]
Wow, you work fast! That's also an interesting catch concerning `is_plain_ascii`. I'd give them a PR if I knew what I was doing—I only know well around 1/2 to 3/4 of `portable_simd` and a little bit of x86; seeing as they use stable simd. If I got into the weeds it would probably be more harmful than helpful. I'll probably circle back at a semi-soon date and take a crack at it. Or, at the very least, do my own ASCII check before `simdutf8` with `portable_simd`. Thank you lots.
