### ISSUE TITLE
Unsafe with enum repr(u8)

### ISSUE THREAD

**Issue by 7ERr0r** [azalea-rs/simdnbt#2]
Well... Just don't use unsafe

https://youtu.be/hBjQ3HqCfxs

```rust
match self {
    Byte(_) => BYTE_ID,
    Short(_) => SHORT_ID,
    Int(_) => INT_ID,
    Long(_) => LONG_ID,
    Float(_) => FLOAT_ID,
    Double(_) => DOUBLE_ID,
    ByteArray(_) => BYTE_ARRAY_ID,
    String(_) => STRING_ID,
    List(_) => LIST_ID,
    Compound(_) => COMPOUND_ID,
    IntArray(_) => INT_ARRAY_ID,
    LongArray(_) => LONG_ARRAY_ID,
}
```

**Comment by 7ERr0r** [comment]
https://github.com/azalea-rs/simdnbt/blob/922701104ab432eea6185a1a5e96211eaeba5bda/simdnbt/src/borrow/mod.rs#L123-L128

**Comment by 7ERr0r** [comment]
Btw i've done borrowed NBT in rust like a year ago and `byteorder` was slow.
So i've made my own reader without `io::Cursor<&'a [u8]>`

https://docs.rs/byteorder/latest/src/byteorder/io.rs.html#347-351

Probably it's visible in compiler explorer, godbolt or something

**Comment by mat-1** [comment]
> Well... Just don't use unsafe
> 
> https://youtu.be/hBjQ3HqCfxs
> 
> ```rust
> match self {
>     Byte(_) => BYTE_ID,
>     Short(_) => SHORT_ID,
>     Int(_) => INT_ID,
>     Long(_) => LONG_ID,
>     Float(_) => FLOAT_ID,
>     Double(_) => DOUBLE_ID,
>     ByteArray(_) => BYTE_ARRAY_ID,
>     String(_) => STRING_ID,
>     List(_) => LIST_ID,
>     Compound(_) => COMPOUND_ID,
>     IntArray(_) => INT_ARRAY_ID,
>     LongArray(_) => LONG_ARRAY_ID,
> }
> ```

Thanks for the issue. I used a cast here because from my testing it was faster than a match statement, so I'm not sure switching is really worth it.

**Comment by mat-1** [comment]
> Btw i've done borrowed NBT in rust like a year ago and `byteorder` was slow. So i've made my own reader without `io::Cursor<&'a [u8]>`
> 
> https://docs.rs/byteorder/latest/src/byteorder/io.rs.html#347-351
> 
> Probably it's visible in compiler explorer, godbolt or something

That's interesting. I did my own benchmarking comparing byteorder to my own implementation but there wasn't any difference. Maybe I didn't implement it optimally or it depends on how the program is compiled or it was a bug in byteorder?

**Comment by 7ERr0r** [comment]
I believe `byteorder` crate generates a lot of LLVM-IR and some simple reads don't get optimized. 
But can't remember what I did 2 years ago. 

> I did my own benchmarking

Maybe it's the same - sorry.
