### ISSUE TITLE
Unsoundness in swap_endianness

### ISSUE THREAD

**Issue by Ciel-MC** [azalea-rs/simdnbt#3]
Simply put, the Vec::from_raw_parts is unsound in swap_endianness because it doesn't fit alignment requirements. Simple example shown below.
```rust
    #[test]
    fn test_swap_endianness_u64_vec() {
        assert_eq!(
            swap_endianness::<u64>(&[1, 2, 3, 4, 5, 6, 7, 8, 8, 7, 6, 5, 4, 3, 2, 1]),
            vec![
                u64::from_le_bytes([8, 7, 6, 5, 4, 3, 2, 1]),
                u64::from_le_bytes([1, 2, 3, 4, 5, 6, 7, 8])
            ]
        );
    }
```
The results when you run the tests in Miri says as much
```
test swap_endianness::tests::test_swap_endianness_u64_vec ... error: Undefined Behavior: constructing invalid value: encountered an unaligned refere
nce (required 8 byte alignment but found 2)
   --> /Users/ciel/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/raw.rs:109:9
    |
109 |         &*ptr::slice_from_raw_parts(data, len)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ constructing invalid value: encountered an unaligned reference (required 8 byte alignment but f
ound 2)
    |
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
    = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
    = note: BACKTRACE:
    = note: inside `std::slice::from_raw_parts::<'_, u64>` at /Users/ciel/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/libra
ry/core/src/slice/raw.rs:109:9: 109:47
    = note: inside `<std::vec::Vec<u64> as std::ops::Deref>::deref` at /Users/ciel/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/r
ust/library/alloc/src/vec/mod.rs:2709:18: 2709:64
    = note: inside `std::vec::partial_eq::<impl std::cmp::PartialEq for std::vec::Vec<u64>>::eq` at /Users/ciel/.rustup/toolchains/nightly-aarch64-a
pple-darwin/lib/rustlib/src/rust/library/alloc/src/vec/partial_eq.rs:16:54: 16:58
note: inside `swap_endianness::tests::test_swap_endianness_u64_vec`
```
Running Miri on your code if you're gonna use unsafe is probably a good idea... 👀 alignment is easy to forget about, in this case, u64 wants alignment of 8 bytes, which the original byte array doesn't fufill

**Comment by Ciel-MC** [comment]
Oh, and it's a double free because you created a vec to the data while the original data can still be backed by a vec. And by the same token, an improper free UB because it is allocated with alignment 1 byte(for u8s), but is deallocated first with alignment of 2(drop in reverse of declaration, so the new vec deallocates first)

In other words, maybe a bit too reckless when going for performance...

**Comment by mat-1** [comment]
Thank you for reporting this!
I believe I've fixed the alignment issue by making it so the `Vec<u8>` in `swap_endianness` is aligned by creating a `Vec<T>` first and then using `Vec::from_raw_parts` to make it into a `Vec<u8>`. I added your proposed test and Miri doesn't complain anymore, but please let me know if I missed something.

**Comment by Ciel-MC** [comment]
> Thank you for reporting this!
> 
> I believe I've fixed the alignment issue by making it so the `Vec<u8>` in `swap_endianness` is aligned by creating a `Vec<T>` first and then using `Vec::from_raw_parts` to make it into a `Vec<u8>`. I added your proposed test and Miri doesn't complain anymore, but please let me know if I missed something.

Hi there, Ive taken a glance and it seems like the original issue is resolved, though I should mention that there could be memory leaks with the new implementation as `with_capacity` actually contracts to be *at least* of the specified capacity, while you assumed that the capacity will be of `data.len()/size_of<T>()`, Im not sure if it can UB, but a memory leak due to part of the allocation being lost when converting from `Vec<T>` to `Vec<u8>` seems very much real

**Comment by Ciel-MC** [comment]
Edit: My exact approach might not work as `slice::from_raw_parts` wants valid memory, and I don't think uninit is valid, you can use zerod(), but there is probably a better way to do it using MaybeUninit's methods at that point. (Or just used ZeroCopy lol)

Also, looking at the docs for `from_raw_parts`, I would probably instead create a `Vec` of `MaybeUninit<T>`(of the appropriate length), create a mutable slice into it(with `slice::from_raw_parts` as the doc recommended), and "memcpy" from the endian-swapped slice into the new slice, which avoids potential mistakes when deconstructing and reconstructing the Vec
